config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tweets do
    resources :comments, only: %I[new edit create update destroy]
    resources :favorites, only: %I[create destroy]
  end
  get 'favorites', to: 'favorites#index'
  get 'admin', to: 'admin#index'

  resources :users
  resources :memos

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tweets#index'
end

app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id         :bigint           not null, primary key
#  body       :string
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
class Tweet < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy, inverse_of: :tweet
  has_many :favorites

  validates :title, presence: true
  validates :body, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %I[show edit update destroy]
  authorize_resource

  def new
    @tweet = Tweet.new
  end

  def show
    @user = @tweet.user
    @user_name = if user_signed_in?
                   current_user.user_name
                 else
                   'ゲスト'
                 end
    @comment = Comment.new
  end

  def index
    @tweets = Tweet.all.order(id: :DESC)
    @user_name = if user_signed_in?
                   current_user.user_name
                 else
                   'ゲスト'
                 end
  end

  def edit; end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      redirect_to tweets_path
    else
      render new_tweet_path
    end
  end

  def update
    @tweet.update(tweet_params)
    redirect_to tweets_path
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:body, :title)
  end
end

app/views/tweets/create.html.erb
<h2>Tweets#create</h2>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/edit.html.erb
<h2><%= link_to "← ", tweets_path, class: "before_page" %>ツイート編集</h2>

<%= form_for @tweet do |f| %>
  <p>
    <%= f.label :title,"タイトル" %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body,"ツイート" %>
    <%= f.text_field :body %>
  </p>
  <%= f.submit '更新', class: "button" %>
<% end %>

app/views/tweets/index.html.erb
<h2>ツイート一覧</h2>

<% @tweets.each do |tweet| %>
  <%= render partial: "layouts/tweet", locals: {tweet: tweet} %>
<% end %>

app/views/tweets/new.html.erb
<h2><%= link_to "← ", tweets_path, class: "before_page" %>新規ツイート作成</h2>
<% if @tweet.errors.any? %>
  <p class="error_message">タイトルとツイートの両方を入力してください。</p>
<% end %>

<%= form_for @tweet do |f| %>
  <p>
    <%= f.label :title,"タイトル" %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body,"ツイート" %>
    <%= f.text_field :body %>
  </p>
  <%= f.submit "新規作成", class: "button" %>
<% end %>

app/views/tweets/show.html.erb
<h2><%= link_to "← ", tweets_path, class: "before_page" %>ツイート内容</h2>

<div class="user-flex">
  <p class="user-image2">
    <% if @tweet.user.image.present? %>
      <%= image_tag @tweet.user.image.url %>
    <% else %>
      <%= image_tag "initial_image.jpg", size: "60x60", class: "rounded-circle" %>
    <% end %>
  </p>
  <div class="user-mini-form">
    <p class="name"><%= link_to @tweet.user.user_name, @tweet.user %></p>
    <p class="email"><%= @tweet.user.email %></p>
  </div>
</div>
<p><span>タイトル: </span><%= @tweet.title %></p>
<p><span>ツイート内容: </span><%= @tweet.body %></p>

<% @tweet.comments.each do |comment| %>
  <hr>
  <p><%= comment.user.user_name %><span>： </span><%= comment.content %></p>
  <% if @user_name == comment.user.user_name %>
    <button class="button"><%= link_to "編集", edit_tweet_comment_path(@tweet, comment.id) %></button>
    <button class="button"><%= link_to "削除", tweet_comment_path(@tweet, comment.id), method: :delete, data: {confirm: "本当に削除しますか？"} %></button>
  <% end %>
<% end %>

<% if user_signed_in? %>
  <%= form_for [@tweet, @comment] do |f| %>
    <hr>
    <%= f.text_field :content, class: "mx-0" %>
    <%= f.submit "コメントする", class: "button", class: "button" %>
  <% end %>
<% end %>