config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tweets do
    resources :comments, only: %I[new edit create update destroy]
    resources :favorites, only: %I[create destroy]
  end
  get 'favorites', to: 'favorites#index'
  get 'admin', to: 'admin#index'

  resources :users
  resources :memos

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tweets#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  image                  :string
#  introduction           :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  user_name              :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_roles
  has_many :roles, through: :user_roles
  has_many :tweets
  has_many :favorites
  has_many :favorite_tweets, through: :favorites, source: :tweet

  validates :user_name, presence: true
  validates :email, presence: true

  mount_uploader :image, ImageUploader

  def admin?
    self.roles.include?(Role.find_by(name: 'admin'))
  end

  def manager?
    self.roles.include?(Role.find_by(name: 'manager'))
  end

  def read_only?
    self.roles.include?(Role.find_by(name: 'read_only'))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %I[show edit update]
  authorize_resource

  def index
    @users = User.all
    @user = if user_signed_in?
              current_user.user_name
            else
              'ゲスト'
            end
  end

  def show
    @favorite_tweets = @user.favorite_tweets
    @tweets = @user.tweets.reverse
  end

  def edit; end

  def update
    @user.update(user_params)
    redirect_to user_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :user_name, :introduction, :image)
  end
end

app/views/users/edit.html.erb
<h2><%= link_to "← ", user_path(@user.id), class: "before_page" %>ユーザー編集</h2>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :user_name,"ユーザーネーム" %>
    <%= f.text_field :user_name %>
  </p>
  <div class="user-flex">
    
    <p class="user-image-form">
      <%= f.label :image,"画像" %>
      <%= f.file_field :image %>
    </p>
  </div>
  <p>
    <%= f.label :email,"メールアドレス" %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :introduction,"自己紹介" %>
    <%= f.text_field :introduction %>
  </p>
  <%= f.submit '更新', class: "button" %>
<% end %>

app/views/users/index.html.erb
<h2>ユーザー一覧</h2>
<hr>
<p><%= @user %>でログインしています。</p>
<% @users.each do |user| %>
  <hr>
  <div class="user-flex">
    <p class="user-image2">
      <% if user.image.present? %>
        <%= image_tag user.image.url %>
      <% else %>
        <%= image_tag "initial_image.jpg", size: "60x60", class: "rounded-circle" %>
      <% end %>
    </p>
    <div class="user-mini-form">
      <p class="name"><%= user.user_name %></p>
      <p class="email"><%= user.email %></p>
    </div>
  </div>
  <p><%= user.introduction %></p>
  <button class="button"><%= link_to "詳細", user_path(user.id) %></button>
  <% if @user == user.user_name %>
    <button class="button"><%= link_to "編集", edit_user_path(user.id) %></button>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h2><%= link_to "← ", users_path, class: "before_page" %><%= @user.user_name %>のマイページ</h2>

<hr>
<div class="user-flex">
  <p class="user-image">
    <% if @user.image.present? %>
      <%= image_tag @user.image.url %>
    <% else %>
      <%= image_tag "initial_image.jpg", size: "60x60", class: "rounded-circle" %>
    <% end %>
  </p>
  <div>
    <p class="user-name"><%= @user.user_name %></p>
    <p class="user-email"><%= @user.email %></p>
  </div>
</div>
<p><span>自己紹介: </span><%= @user.introduction %></p>

<% if current_user == @user %>
  <button class="button"><%= link_to "編集", edit_user_path(@user.id) %></button>
<% end %>

<% @tweets.each do |tweet| %>
  <%= render partial: "layouts/tweet", locals: {tweet: tweet} %>
<% end %>

<% @favorite_tweets.each do |tweet| %>
  <hr>
  <p><span>お気に入りのツイート: </span><%=link_to tweet.title, tweet_path(tweet.id) %></p>
<% end %>