config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tweets do
    resources :comments, only: %I[new edit create update destroy]
    resources :favorites, only: %I[create destroy]
  end
  get 'favorites', to: 'favorites#index'
  get 'admin', to: 'admin#index'

  resources :users
  resources :memos

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tweets#index'
end

app/models/memo.rb
# == Schema Information
#
# Table name: memos
#
#  id         :bigint           not null, primary key
#  content    :text
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
class Memo < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: %I[show edit update destroy]
  authorize_resource

  def index
    @memos = Memo.where(user: current_user).order(updated_at: :desc)
  end

  def show; end

  def new
    @memo = Memo.new
  end

  def edit; end

  def create
    Memo.create!(memo_params)
    redirect_to memos_path
  end

  def update
    @memo.update!(memo_params)
    redirect_to memos_path
  end

  def destroy
    @memo.destroy!
    redirect_to memos_path
  end

  private

  def set_memo
    @memo = Memo.find(params[:id])
  end

  def memo_params
    params.require(:memo).permit(:title, :content).merge(user: current_user)
  end
end

app/views/memos/edit.html.erb
<h2><%= link_to "← ", memos_path, class: "before_page" %>メモの編集</h2>

<%= form_for @memo do |f| %>
  <div class="row mx-0 my-3">
    <%= f.label :title, "タイトル", class: "col-3 p-0 m-0" %>
    <%= f.text_field :title, class: "col-9" %>
  </div>
  <div class="row mx-0 mb-3">
    <%= f.label :content, "内容", class: "col-3 p-0 m-0" %>
    <%= f.text_area :content, class: "col-9 px-2", rows: "10" %>
  </div>
  <%= f.submit "更新", class: "button" %>
<% end %>

app/views/memos/index.html.erb
<h2>メモ一覧</h2>

<% @memos.each do |memo| %>
  <hr>
  <div class="memo">
    <div class="row mb-4">
      <div class="col-9 pr-0"><h3><%= memo.title %></h3></div>
      <div class="col-3 p-0">
        <%= link_to edit_memo_path(memo.id), class: "btn-circle mx-2" do %><i class="fas fa-pen-nib"></i><% end %>
        <%= link_to memo_path(memo.id), class: "btn-circle", method: :delete, data: {confirm: "本当に削除しますか？"} do %><i class="fas fa-trash"></i><% end %>
      </div>
    </div>
    <pre class="m-0"><%= memo.content %></pre>
  </div>
<% end %>

app/views/memos/new.html.erb
<h2><%= link_to "← ", memos_path, class: "before_page" %>メモの作成</h2>

<%= form_for @memo do |f| %>
  <div class="row mx-0 my-3">
    <%= f.label :title, "タイトル", class: "col-3 p-0 m-0" %>
    <%= f.text_field :title, class: "col-9" %>
  </div>
  <div class="row mx-0 mb-3">
    <%= f.label :content, "内容", class: "col-3 p-0 m-0" %>
    <%= f.text_area :content, class: "col-9 px-2", rows: "10" %>
  </div>
  <%= f.submit "作成", class: "button" %>
<% end %>

app/views/memos/show.html.erb
<h2><%= link_to "← ", memos_path, class: "before_page" %>メモ</h2>

<div class="memo">
  <div class="row mb-4">
    <div class="col-9 pr-0"><h3><%= @memo.title %></h3></div>
    <div class="col-3 p-0">
      <%= link_to edit_memo_path(@memo.id), class: "btn-circle mx-2" do %><i class="fas fa-pen-nib"></i><% end %>
      <%= link_to memo_path(@memo.id), class: "btn-circle", method: :delete, data: {confirm: "本当に削除しますか？"} do %><i class="fas fa-trash"></i><% end %>
    </div>
  </div>
  <pre class="m-0"><%= @memo.content %></pre>
</div>