config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tweets do
    resources :comments, only: %I[new edit create update destroy]
    resources :favorites, only: %I[create destroy]
  end
  get 'favorites', to: 'favorites#index'
  get 'admin', to: 'admin#index'

  resources :users
  resources :memos

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tweets#index'
end

app/views/layouts/_favorite.html.erb
<div id="like-<%= tweet.id %>">
  <p class="pt-2">
    <% if user_signed_in? %>
      <% if tweet.favorited_by?(current_user) %> <!-- ログインしているユーザーがファボしたかどうかで分岐 -->
        <span class="mr-2"><%=link_to "❤️ ", tweet_favorite_path(id: tweet.id, tweet_id: tweet.id), class: "text-decoration-none heart", method: :delete, remote: true %></span>
      <% else %>
        <span class="mr-2"><%=link_to "🤍 ", tweet_favorites_path(tweet.id), class: "text-decoration-none heart", method: :post, remote: true %></span>
      <% end %>
    <% else %>
      <span class="mr-2">🤍</span>
    <% end %>
    <%= tweet.favorites.count %>
    <span class="ml-4 mr-2"><%=link_to "💬 ", tweet_path(tweet.id), class: "text-decoration-none" %></span>
    <%= tweet.comments.count %>
  </p>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <p><i class="fas fa-kiwi-bird"></i><%= ApplicationHelper::APP_NAME %></p>
</div>

app/views/layouts/_tweet.html.erb
<hr>
<div class="user-flex">
  <p class="user-image2">
    <% if tweet.user.image.present? %>
      <%= image_tag tweet.user.image.url %>
    <% else %>
      <%= image_tag "initial_image.jpg", size: "60x60", class: "rounded-circle" %>
    <% end %>
  </p>
  <div class="user-mini-form">
    <p class="name"><%= link_to tweet.user.user_name, tweet.user %></p>
    <p class="email"><%= tweet.user.email %></p>
  </div>
</div>
<p><span>タイトル: </span><%= tweet.title %></p>
<p><span>ツイート内容: </span><%= tweet.body %></p>
<button class="button"><%= link_to "詳細", tweet_path(tweet.id) %></button>
<% if @user_name == tweet.user.user_name %>
  <button class="button"><%= link_to "編集", edit_tweet_path(tweet.id) %></button>
  <button class="button"><%= link_to "削除", tweet_path(tweet.id), method: :delete, data: {confirm: "本当に削除しますか？"} %></button>
<% end %>
<%# いいね機能 %>
<%= render partial: "layouts/favorite", locals: {tweet: tweet} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>簡易twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="constitution">
      <div class="side-menu">
        <div class="side-menu-container">
          <ul>
            <% unless user_signed_in? %>
              <li><button class="side-button mb-3"><%= link_to new_user_registration_path do %><i class="fas fa-palette mr-2"></i>新規登録<% end %></button></li>
              <li><button class="side-button mb-3"><%= link_to new_user_session_path do %><i class="fas fa-sign-in-alt mr-2"></i>ログイン<% end %></button></li>
            <% end %>
            <li><button class="side-button mb-3"><%= link_to tweets_path do %><i class="fas fa-home mr-2"></i>ツイート 一覧<% end %></button></li>
            <li><button class="side-button mb-3"><%= link_to users_path do %><i class="fas fa-user mr-2"></i>ユーザー 一覧<% end %></button></li>
            <% if user_signed_in? %>
              <li><button class="side-button mb-3"><%= link_to memos_path do %><i class="far fa-sticky-note mr-2"></i>メモ帳<% end %></button></li>
              <li><button class="side-button mb-3"><%= link_to favorites_path do %><i class="far fa-thumbs-up mr-2"></i>お気に入り<% end %></button></li>
              <li><button class="side-button mb-3"><%= link_to user_path(current_user.id) do %><i class="far fa-address-card mr-2"></i>マイページ<% end %></button></li>
              <li><button class="side-button mb-3"><%= link_to destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"} do %><i class="fas fa-sign-out-alt mr-2"></i>ログアウト<% end %></button></li>
            <% end %>
          </ul>
          <% if request.path.include?("tweets") || request.path == "/" %>
            <li><div class="create-tweet"><%= link_to "Tweet 投稿", new_tweet_path %></div></li>
          <% elsif request.path.include?("memos") %>
            <li><div class="create-tweet"><%= link_to "メモ作成", new_memo_path %></div></li>
          <% end %>
        </div>
      </div>
      <div class="main">
        <div class="main-container">
          <%= yield %>
        </div>
      </div>
      <div class="other">
        <div class="other-container">
          <div class="user">
            <% if user_signed_in? %>
            <div class="user-flex">
              <p class="user-image2">
                <% if current_user.image.present? %>
                  <%= image_tag current_user.image.url %>
                <% else %>
                  <%= image_tag "initial_image.jpg", size: "60x60", class: "rounded-circle" %>
                <% end %>
              </p>
              <div class="user-mini-form">
                <p class="name"><%= link_to current_user.user_name, current_user %></p>
                <p class="email"><%= current_user.email %></p>
              </div>
            </div>
            <p><%= current_user.introduction %></p>
            <% else %>
            <h3>ゲスト</h3>
            <% end %>
          </div>
          <div class="news">
            <h3>最近の話題</h3>
            <a class="twitter-timeline" data-tweet-limit="10" href="https://twitter.com/YahooNewsTopics?ref_src=twsrc%5Etfw">Tweets by YahooNewsTopics</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>